### ISSUE TITLE
Make maps awesome

### ISSUE THREAD

**Issue by stringfellow** [openwater/h2o-really#5]
Use TastyPie API (to be set up in #4) to filter and get data onto map sensibly.

Should be able to inspect each point as well, and maybe see a time-series over an area.

**Comment by jimr** [comment]
Some more ideas for with which to make maps more awesome:
- instead of clustering, maybe use a spiderifier: https://github.com/jawj/OverlappingMarkerSpiderfier-Leaflet
- time slider for showing observations added over time: https://github.com/dwilhelm89/LeafletSlider
- heatmaps: http://www.patrick-wied.at/static/heatmapjs/example-heatmap-leaflet.html

**Comment by stringfellow** [comment]
Closing this since they are pretty awesome. More refinements will need more refined wording in tickets!
